### ISSUE TITLE
Invalid date or strptime format

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/technical-metadata-service#120]
```
ArgumentError: invalid date or strptime format - `2020-03-26 15:36:20+0000' `UTC %Y-%m-%d %H:%M:%S%z'
```

https://app.honeybadger.io/projects/68956/faults/62385673

**Comment by jcoyne** [comment]
The problem here is that the data from media info, specifically the Encoded_Date seems to not consistently have `UTC` as a prefix.  This one doesn't:

```
mediainfo -f --Output=JSON /dor/workspace/zt/871/kw/5039/zt871kw5039/content/zt871kw5039_pm.wav
```
produces
```
...
"Encoded_Date": "2020-03-27 16:47:11",
...
```

Whereas the test data we have does have UTC. 

So, I'm not sure if we should add a conditional or just not capture the date when we don't have a TZ.

**Comment by andrewjbtw** [comment]
Copying over my comment from Slack:

I want to capture the date even if we don’t have TZ. I looked through the mediainfo help to see if there’s a way to force the TZ but I don’t see one. It’s possible that some source files just don’t have it and mediainfo can’t guess it.

**Comment by jcoyne** [comment]
@andrewjbtw we are casting it to a UTC time, but that seems inappropriate for something that is not UTC originally, right?

**Comment by andrewjbtw** [comment]
@jcoyne Yeah, I think if the field is not consistently identified as UTC then we might be introducing faulty data if we're assuming it's UTC.
