### ISSUE TITLE
[technical-metadata-service/prod] ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/technical-metadata-service#167]
The old HB link expired (from errors in 2020), adding a new one: https://app.honeybadger.io/projects/68956/faults/85453750

**Comment by ndushay** [comment]
this hasn't shown up in honeybadger in 2 years.

**Comment by andrewjbtw** [comment]
I've made copies of the two PDFs from [nk407ty6214](https://argo.stanford.edu/view/druid:nk407ty6214) and [zt417wm6774](https://argo.stanford.edu/view/druid:zt417wm6774) so they can be tested on stage or locally.

I did a quick check to see if either file generated errors in a PDF viewer and didn't see any issues. Since the depositor is waiting for these files, I'm going to get them deposited by manually skipping the tech MD step and reproduce the issue with stage druids.
