### ISSUE TITLE
Generate tech-md for SDR objects not yet included (AND ... for all objects, in future)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/technical-metadata-service#349]
related to #348

Implement a way to generate technical metadata for objects that are in SDR but aren't (yet) in tech md database, that can be re-used in the future to re-generate technical metadata for all objects, or a (potentially large) subset of objects.

Requirements:
- it must not slow down accessioning appreciably (unlikely, because I believe tech md is generated as a background job)
- it hopefully won't require creating a new version of the object just for this purpose (?), or otherwise running it through accessioning.
- it must not tank this service due to a zillion objects in the queues
- it should be watched to ensure we don't hammer HoneyBadger with errors.

Does anything need to happen outside of the technical metadata service itself (e.g. workflow step or event logged or ...)? 

I am assuming it would be stupid to convert technicalMetadata.xml, and instead the object should run through this app's processing.

**Comment by andrewjbtw** [comment]
The `/pres-#` mounts are accessible from the tech md server to make it possible to regenerate the tech md by reading the preserved files without reaccessioning. My overall goal is to be able to regenerate tech md if we make significant changes to either the tools or our schema, such as wanting to track an attribute we hadn't tracked before.

We should definitely not read the technicalMetadata.xml, which is of limited use when it's correct and is often just plain wrong. I found lots of misidentified files when sampling the output, for example.

**Comment by ndushay** [comment]
I am assuming nothing needs to happen outside of tech-md-service when generating or re-generating technical metadata.

**Comment by jcoyne** [comment]
Is there a use case for doing this work?

**Comment by andrewjbtw** [comment]
It's not a useful service without covering the whole repository. This is finishing work left incomplete two years ago when we only did enough to keep techMD from being a bottleneck for Google Books. It's like making sure we index all of the druids.

Without it, I'll continue to come up with my own scripts to answer questions like "what formats are in the repository?" or "what is the duration of all the video in this collection?" Knowing what's in your repository is essential to managing it responsibly. SDR has never met this need and can't unless we can get tech md for everything in it.

**Comment by justinlittman** [comment]
Update on techmd retro generation: After experimenting with smaller configurations and numbers of items, retro techmd generation is now running on techmd-prod-worker-b with 2 processes of 4 threads. Also, I am currently queueing all ~1.7 million items that need retro conversion. Note that:
* The process of queueing is slow and may take > 1 week.
* Retro techmd generation could take many months to run. It’s not easy to estimate.
* We could allocate additional resources, but this will place an additional load on pres storage/ceph.
* The deploy for techmd-prod-worker-b is in a separate branch, not main: https://github.com/sul-dlss/technical-metadata-service/pull/354.
* Workers for techmd-prod-worker-b are running as the pres user instead of the techmd user. To make everything place well together, techmd-prod-worker-b is deployed separately using the retro environment instead of the prod environment. We will probably want to periodically rebase the deploy branch and redeploy to keep techmd-prod-worker-b up to date.

You can monitor the progress: https://techmd-prod.stanford.edu/queues/busy

If there is ever a problem, the fastest way to things down is to quiet/stop the workers from that page.

**Comment by ndushay** [comment]
Andrew says he is fine with this process taking months.

**Comment by justinlittman** [comment]
This work is completed. Leaving this ticket open until the retro infrastructure is decommissioned.
