### ISSUE TITLE
Install libvips for image metadata generation

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/technical-metadata-service#97]
Please install libvips as a possible alternative to using exiftool for image metadata: 
https://github.com/libvips/libvips

I had a chat with @calavano about image technical metadata and he pointed out some issues with the reliability and accuracy of what exiftool reports, especially when an image contains more than once source of metadata (e.g. in the header, but also in EXIF data). He suggested libvips as a more accurate alternative.

**Comment by jcoyne** [comment]
@andrewjbtw won't vips only work for TIFFs?  What about other formats (I'm thinking from Hydrus).

**Comment by andrewjbtw** [comment]
They claim wider support, but I haven't used it before (installing locally now).

"It supports a good range of image formats, including JPEG, TIFF, PNG, WebP, FITS, Matlab, OpenEXR, PDF, SVG, HDR, PPM, CSV, GIF, Analyze, NIfTI, DeepZoom, and OpenSlide. It can also load images via ImageMagick or GraphicsMagick, letting it load formats like DICOM."

**Comment by jcoyne** [comment]
@andrewjbtw fantastic.  How about JPEG2000?

**Comment by andrewjbtw** [comment]
Good question. Looking at the documentation, I'm not clear on how to just get metadata from it, rather than manipulate images.

**Comment by andrewjbtw** [comment]
Looks like ```vipsheader``` is the command to get metadata.

```
$ vipsheader -a Screenshot\ at\ 2020-01-23\ 23-04-48.png 
Screenshot at 2020-01-23 23-04-48.png: 1338x712 uchar, 3 bands, srgb, pngload
width: 1338
height: 712
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 2.834
yres: 2.834
filename: Screenshot at 2020-01-23 23-04-48.png
vips-loader: pngload
```
However, JPEG2000 isn't supported:
```
$ vipsheader -a cb303zr7917_00_0001.jp2 
vipsheader: VipsForeignLoad: "cb303zr7917_00_0001.jp2" is not a known file format
```
So we either shouldn't use it, or we need to use a different tool on JP2.

**Comment by calavano** [comment]
libvips can support JPEG2000 through its ImageMagick/GraphicsMagick wrapper. 
The build of libvips provided by the remi repo has this option turned on.
```
$ vipsheader -a 247alecon00.jp2 
247alecon00.jp2: 3778x2884 uchar, 3 bands, srgb, magickload
width: 3778
height: 2884
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: 247alecon00.jp2
vips-loader: magickload
magick-date:create: 2020-03-02T23:14:31+00:00
magick-date:modify: 2020-03-02T23:14:31+00:00
n-pages: 1
```
We would need to be careful about loading large images through ImageMagick, you can have similar performance problems we've had with image conversion with just using `identify -verbose`. Using ImageMagick directly with `identify -verbose` or another application/wrapper that uses its libraries  (like RMagick or minimagick) seems to want to load the whole image instead of just checking header information. I've had a few images where `identify -verbose` would eat up 10s of GBs of RAM.

`vipsheader` can be much faster. vs `identify -verbose` e.g:
```
$ time vipsheader -a bigtiff.tif   
<snip>
real    0m0.067s
user    0m0.033s
sys     0m0.006s
$ time identify -verbose bigtiff.tif 
<snip>
real    2m46.711s
user    1m29.816s
sys     0m9.396s
```

For alternatives to reading jp2 information, two good options are Kakadu `kdu_jp2info` and OpenJPEG `opj2_dump`

**Comment by jcoyne** [comment]
Is there  common data model we would use to harmonize the output of these tools?  It's unclear to me what the user need is in this case. Can you articulate that?

**Comment by justinlittman** [comment]
And are we convinced that the reliability and accuracy issues with exiftool are significant enough that they obviate it's value for these purposes? (In other words, is it good enough if detailed work with a file would involve running through new tools anyways.)

**Comment by calavano** [comment]
exiftool would very likely be good enough in the vast majority of cases. I raised it as a potential source of inaccurate data for areas where it can report EXIF data even if it differs from the actual underlying image data.

A big part of the question of it being viable or not will be around how what fields we will be saving. When @andrewjbtw and chatted briefly about this, we didn't really come to any conclusions. If using it to capture a bunch of EXIF fields, then it would likely be most optimal to just use exiftool and accept the risk. If we're only after more basic image information, then I would lean towards something that only looks at the image data.

An example of an image that is currently failing in jp2-create because of this problem is with `cb221rt2939`.
```
$ exiftool farmworkers\ 010.jpg
Samples Per Pixel               : 4
Color Components                : 1
```
The underlying image data is only 1 color channel, so SamplesPerPixel in this case is wrong. ColorComponents doesn't return anything for tiff or jp2. For this file identify and vipsheader report the correct number of color channels.

**Comment by jcoyne** [comment]
@calavano that is super helpful, thank you.

**Comment by andrewjbtw** [comment]
Thanks for all of the input. I haven't had time to get back to this. I'm not sure where this leaves us as far as minimum fields and which tool(s) to use, but given the complexity I'm in favor of not holding up deployment of the new techMD service on these details.

Overall, I am in favor of storing only a small amount of fields, but with accurate information. If we can combine libvips and a JP2 tool, that seems ideal. 

If not, I think just the file type and basic dimensions will probably be fine until we learn there's some other field where there's an actual need. But I would like to be able to get 

1. color/grayscale/black and white
2. whether a tiff is a multi-image tiff (because these can be display/compatibility problems down the line)

**Comment by andrewjbtw** [comment]
@calavano How much of a risk do you think it would be to accept exiftool's "Photometric interpretation" value?

In the sample above, photometric interpretation is "BlackisZero"

```
$ exiftool -"PhotometricInterpretation" farmworkers\ 010.jpg 
Photometric Interpretation      : BlackIsZero
```
This is the same value I see with both vipsheader and identify, looking at their fuller output.

**Comment by calavano** [comment]
@andrewjbtw Do you mean as a replacement for 'Color Components' or in general? Note that 'PhotometricInterpretation' will not be a universally available. 

You can use ImageMagick's built-in images to generate some basic images that will be free of a lot of the extra data that applications like Photoshop will tend to stick in it.

A lot of these tools do not normalize all of the fields between image formats. There could be a chance that we would need to create a mapping between desired fields and mime-types.

```
$ convert rose: -type Grayscale grayscale.jpg
$ exiftool grayscale.jpg
ExifTool Version Number         : 11.70
File Name                       : grayscale.jpg
Directory                       : .
File Size                       : 1489 bytes
File Modification Date/Time     : 2020:03:10 13:59:37-07:00
File Access Date/Time           : 2020:03:10 13:59:37-07:00
File Inode Change Date/Time     : 2020:03:10 13:59:37-07:00
File Permissions                : rw-rw-r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
Image Width                     : 70
Image Height                    : 46
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 1
Image Size                      : 70x46
Megapixels                      : 0.003

$ vipsheader -a grayscale.jpg
grayscale.jpg: 70x46 uchar, 1 band, b-w, jpegload
width: 70
height: 46
bands: 1
format: uchar
coding: none
interpretation: b-w
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: grayscale.jpg
vips-loader: jpegload
jpeg-multiscan: 0
jpeg-chroma-subsample: 4:4:4
```

**Comment by andrewjbtw** [comment]
Based on further discussion off-ticket, we've decided to hold off on a libvips + imageMagick solution at this point because the complexity of reconciling image metadata for different types/from different tools outweighs the need to move to the new technical metadata service. I'm going to close this ticket and we can open a new one if we pick this up later.
